import Link from "next/link";
import { redirect } from "next/navigation";
import { PrintButton } from "@/components/PrintButton";
import { requireOwnerOrManagerAccess } from "@/lib/auth/access";
import { businessSettings } from "@/lib/business-settings";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import {
  calculateManagerClosingSummary,
  getManagerClosingSnapshot,
} from "@/lib/manager-closing";

function formatMoney(amount: number) {
  return `AED ${amount.toFixed(2)}`;
}

function parseDateParam(date: string) {
  return /^\d{4}-\d{2}-\d{2}$/.test(date);
}

function formatGeneratedAt() {
  return new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Asia/Dubai",
  }).format(new Date());
}

export default async function ManagerClosingPrintPage({
  params,
}: {
  params: Promise<{ date: string }>;
}) {
  const { profile } = await requireOwnerOrManagerAccess();
  const { date } = await params;

  if (!parseDateParam(date)) {
    redirect("/manager/closing");
  }

  const snapshot = await getManagerClosingSnapshot(date);
  const supabase = await createSupabaseServerClient();
  const { data: profileRows } = await supabase.from("profiles").select("id, full_name");
  const profileMap = new Map(
    ((profileRows ?? []) as Array<{ id: string; full_name: string | null }>).map(
      (row) => [row.id, row.full_name] as const,
    ),
  );
  const closing = snapshot.existingClosing;
  const summary = calculateManagerClosingSummary({
    entries: snapshot.entries,
    expenses: snapshot.expenses,
    actualCash: closing?.actual_cash ?? 0,
  });
  const generatedAt = formatGeneratedAt();

  return (
    <main className="min-h-screen bg-zinc-50 text-zinc-950 print:bg-white">
      <style>{`
        @media print {
          @page {
            size: A4;
            margin: 12mm;
          }
        }
      `}</style>

      <div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 lg:px-8 print:max-w-none print:px-0 print:py-0">
        <div className="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm print:border-zinc-300 print:bg-white print:shadow-none">
          <div className="flex flex-wrap items-start justify-between gap-4 print:hidden">
            <div>
              <Link
                href={`/manager/closing/${date}`}
                className="text-sm font-medium text-zinc-700 underline-offset-4 hover:underline"
              >
                Back to closing
              </Link>
              <h1 className="mt-2 text-2xl font-semibold tracking-tight">
                Daily Closing Report
              </h1>
            </div>
            <PrintButton className="rounded-2xl bg-zinc-950 px-4 py-3 text-sm font-medium text-white" />
          </div>

          <div className="hidden print:block">
            <h1 className="text-2xl font-semibold tracking-tight">
              Daily Closing Report
            </h1>
          </div>

          <div className="mt-4 grid gap-3 text-sm text-zinc-600 sm:grid-cols-2 print:text-black">
            <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Company
              </p>
              <p className="mt-1 text-base font-semibold text-zinc-950">
                {businessSettings.businessName}
              </p>
            </div>
            <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Closing date
              </p>
              <p className="mt-1 text-base font-semibold text-zinc-950">{date}</p>
            </div>
            <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Generated by
              </p>
              <p className="mt-1 text-base font-semibold text-zinc-950">
                {profile.role === "owner" ? "Owner" : "Manager"} view
              </p>
            </div>
            <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Generated at
              </p>
              <p className="mt-1 text-base font-semibold text-zinc-950">
                {generatedAt}
              </p>
            </div>
          </div>

          <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3 print:grid-cols-3">
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Total approved sales
              </p>
              <p className="mt-2 text-xl font-semibold">
                {formatMoney(summary.totalApprovedSales)}
              </p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Total expenses
              </p>
              <p className="mt-2 text-xl font-semibold">
                {formatMoney(summary.totalExpenses)}
              </p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Net balance
              </p>
              <p className="mt-2 text-xl font-semibold">
                {formatMoney(summary.netBalance)}
              </p>
            </article>
          </div>

          <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4 print:grid-cols-4">
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Cash total
              </p>
              <p className="mt-2 text-xl font-semibold">{formatMoney(summary.cashTotal)}</p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Card total
              </p>
              <p className="mt-2 text-xl font-semibold">{formatMoney(summary.cardTotal)}</p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Online total
              </p>
              <p className="mt-2 text-xl font-semibold">
                {formatMoney(summary.onlineTotal)}
              </p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Cash expense total
              </p>
              <p className="mt-2 text-xl font-semibold">
                {formatMoney(summary.cashExpenseTotal)}
              </p>
            </article>
          </div>

          <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3 print:grid-cols-3">
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Expected cash
              </p>
              <p className="mt-2 text-xl font-semibold">
                {formatMoney(summary.expectedCash)}
              </p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Actual cash
              </p>
              <p className="mt-2 text-xl font-semibold">
                {formatMoney(summary.actualCash)}
              </p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Cash difference
              </p>
              <p className="mt-2 text-xl font-semibold">
                {formatMoney(summary.cashDifference)}
              </p>
            </article>
          </div>

          <div className="mt-6 rounded-3xl border border-zinc-200 bg-white p-5 print:border-zinc-300 print:shadow-none">
            <h2 className="text-lg font-semibold tracking-tight">
              Closing details
            </h2>
            <div className="mt-4 grid gap-3 text-sm text-zinc-700 sm:grid-cols-2 print:text-black">
              <div>
                <span className="block text-zinc-500">Closed by</span>
                <span className="font-medium">
                  {closing
                    ? profileMap.get(closing.manager_id) ??
                      `User ${closing.manager_id.slice(0, 8)}`
                    : "Not closed yet"}
                </span>
              </div>
              <div>
                <span className="block text-zinc-500">Created at</span>
                <span className="font-medium">
                  {closing?.created_at
                    ? new Intl.DateTimeFormat("en", {
                        dateStyle: "medium",
                        timeStyle: "short",
                        timeZone: "Asia/Dubai",
                      }).format(new Date(closing.created_at))
                    : "Not available"}
                </span>
              </div>
              <div className="sm:col-span-2">
                <span className="block text-zinc-500">Notes</span>
                <span className="font-medium">{closing?.notes || "—"}</span>
              </div>
            </div>
          </div>

          <div className="mt-6 rounded-2xl border border-zinc-200 bg-zinc-50 p-4 text-sm text-zinc-600 print:bg-white">
            Daily closing does not calculate or deduct commission.
          </div>
        </div>
      </div>
    </main>
  );
}
