import Link from "next/link";
import { PrintButton } from "@/components/PrintButton";
import { requireOwnerOrManagerAccess } from "@/lib/auth/access";
import { getBusinessSettings } from "@/lib/business-settings";
import {
  formatReportDateLabel,
  getCurrentReportDateString,
  getManagerStaffDailyReport,
  isIsoDate,
} from "@/lib/manager-staff-daily-report";

function formatMoney(amount: number) {
  return `AED ${amount.toFixed(2)}`;
}

function formatGeneratedAt() {
  return new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Asia/Dubai",
  }).format(new Date());
}

export default async function ManagerStaffDailyReportPrintPage({
  searchParams,
}: {
  searchParams: Promise<{ date?: string }>;
}) {
  const { profile } = await requireOwnerOrManagerAccess();
  const { date: dateParam } = await searchParams;
  const selectedDate = isIsoDate(dateParam)
    ? dateParam
    : getCurrentReportDateString();
  const [report, settings] = await Promise.all([
    getManagerStaffDailyReport(selectedDate),
    getBusinessSettings(),
  ]);
  const generatedAt = formatGeneratedAt();

  return (
    <main className="min-h-screen bg-zinc-50 text-zinc-950 print:bg-white">
      <style>{`
        @media print {
          @page {
            size: A4;
            margin: 12mm;
          }
        }
      `}</style>

      <div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 lg:px-8 print:max-w-none print:px-0 print:py-0">
        <div className="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm print:border-zinc-300 print:bg-white print:shadow-none">
          <div className="flex flex-wrap items-start justify-between gap-4 print:hidden">
            <div>
              <Link
                href={`/manager/reports/staff-daily?date=${report.date}`}
                className="text-sm font-medium text-zinc-700 underline-offset-4 hover:underline"
              >
                Back to report
              </Link>
              <h1 className="mt-2 text-2xl font-semibold tracking-tight">
                Daily Staff Performance Report
              </h1>
            </div>
            <PrintButton className="rounded-2xl bg-zinc-950 px-4 py-3 text-sm font-medium text-white" />
          </div>

          <div className="hidden print:block">
            <h1 className="text-2xl font-semibold tracking-tight">
              Daily Staff Performance Report
            </h1>
          </div>

          <div className="mt-4 grid gap-3 text-sm text-zinc-600 sm:grid-cols-2 print:text-black">
            <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Business name
              </p>
              <p className="mt-1 text-base font-semibold text-zinc-950">
                {settings.businessName}
              </p>
            </div>
            <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Selected date
              </p>
              <p className="mt-1 text-base font-semibold text-zinc-950">
                {formatReportDateLabel(report.date)}
              </p>
            </div>
            <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Generated by
              </p>
              <p className="mt-1 text-base font-semibold text-zinc-950">
                {profile.role === "owner" ? "Owner" : "Manager"} view
              </p>
            </div>
            <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Generated at
              </p>
              <p className="mt-1 text-base font-semibold text-zinc-950">
                {generatedAt}
              </p>
            </div>
          </div>

          <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3 print:grid-cols-3">
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Total approved sales
              </p>
              <p className="mt-2 text-xl font-semibold">
                {formatMoney(report.summary.totalApprovedSales)}
              </p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Approved entries
              </p>
              <p className="mt-2 text-xl font-semibold">
                {report.summary.approvedEntriesCount}
              </p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Pending entries
              </p>
              <p className="mt-2 text-xl font-semibold">
                {report.summary.pendingEntriesCount}
              </p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Rejected entries
              </p>
              <p className="mt-2 text-xl font-semibold">
                {report.summary.rejectedEntriesCount}
              </p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Total entries
              </p>
              <p className="mt-2 text-xl font-semibold">
                {report.summary.totalEntriesCount}
              </p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Top staff
              </p>
              <p className="mt-2 text-xl font-semibold">
                {report.summary.topStaffName || "No data"}
              </p>
              <p className="mt-1 text-sm text-zinc-600">
                {formatMoney(report.summary.topStaffApprovedSales)}
              </p>
            </article>
          </div>

          <div className="mt-6 grid gap-4">
            {report.staffRows.length === 0 ? (
              <div className="rounded-3xl border border-dashed border-zinc-200 bg-zinc-50 p-5 text-sm text-zinc-600">
                No service entries found for this date.
              </div>
            ) : null}

            {report.staffRows.map((staff) => (
              <article
                key={staff.staff_id}
                className="rounded-3xl border border-zinc-200 bg-white p-5 print:border-zinc-300 print:bg-white print:shadow-none"
              >
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <h3 className="text-base font-semibold text-zinc-950">
                      {staff.staff_name || "Unknown staff"}
                    </h3>
                    <p className="mt-1 text-sm text-zinc-600">{staff.staff_id}</p>
                  </div>
                  <span className="rounded-full bg-zinc-100 px-3 py-1 text-xs font-medium uppercase tracking-wide text-zinc-700 print:bg-zinc-200">
                    Daily
                  </span>
                </div>

                <div className="mt-4 grid gap-3 text-sm text-zinc-700 sm:grid-cols-2 xl:grid-cols-5 print:text-black">
                  <div>
                    <span className="block text-zinc-500">Approved sales</span>
                    <span className="font-medium">
                      {formatMoney(staff.approvedSalesTotal)}
                    </span>
                  </div>
                  <div>
                    <span className="block text-zinc-500">Approved entries</span>
                    <span className="font-medium">{staff.approvedEntriesCount}</span>
                  </div>
                  <div>
                    <span className="block text-zinc-500">Pending entries</span>
                    <span className="font-medium">{staff.pendingEntriesCount}</span>
                  </div>
                  <div>
                    <span className="block text-zinc-500">Rejected entries</span>
                    <span className="font-medium">{staff.rejectedEntriesCount}</span>
                  </div>
                  <div>
                    <span className="block text-zinc-500">Total entries</span>
                    <span className="font-medium">{staff.totalEntriesCount}</span>
                  </div>
                </div>
              </article>
            ))}
          </div>

          <div className="mt-6 rounded-2xl border border-zinc-200 bg-zinc-50 p-4 text-sm text-zinc-600 print:bg-white">
            Daily staff performance does not calculate commission.
          </div>
        </div>
      </div>
    </main>
  );
}
