import Link from "next/link";
import { redirect } from "next/navigation";
import { PrintButton } from "@/components/PrintButton";
import { requireOwnerOrManagerAccess } from "@/lib/auth/access";
import { getBusinessSettings } from "@/lib/business-settings";
import {
  formatMonthLabel,
  getMonthlyPayoutMonthData,
} from "@/lib/owner-payouts";

function formatMoney(amount: number) {
  return `AED ${amount.toFixed(2)}`;
}

function parseMonthParams(yearParam: string, monthParam: string) {
  const year = Number(yearParam);
  const month = Number(monthParam);

  if (!Number.isInteger(year) || !Number.isInteger(month) || month < 1 || month > 12) {
    return null;
  }

  return { year, month };
}

function formatGeneratedAt() {
  return new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Asia/Dubai",
  }).format(new Date());
}

export default async function OwnerPayoutPrintPage({
  params,
}: {
  params: Promise<{ year: string; month: string }>;
}) {
  const { profile } = await requireOwnerOrManagerAccess();
  const { year: yearParam, month: monthParam } = await params;
  const parsed = parseMonthParams(yearParam, monthParam);

  if (!parsed) {
    redirect("/owner/payouts");
  }

  const { year, month } = parsed;
  const monthData = await getMonthlyPayoutMonthData(year, month);
  const settings = await getBusinessSettings();
  const generatedAt = formatGeneratedAt();

  const totals = monthData.payouts.reduce(
    (acc, payout) => {
      acc.approvedSales += Number(payout.total_approved_sales);
      acc.commissionAmount += Number(payout.commission_amount);
      acc.deductions += Number(payout.deductions);
      acc.advanceDeduction += Number(payout.advance_deduction);
      acc.finalPayable += Number(payout.final_payable);
      return acc;
    },
    {
      approvedSales: 0,
      commissionAmount: 0,
      deductions: 0,
      advanceDeduction: 0,
      finalPayable: 0,
    },
  );

  return (
    <main className="min-h-screen bg-zinc-50 text-zinc-950 print:bg-white">
      <style>{`
        @media print {
          @page {
            size: A4;
            margin: 12mm;
          }
        }
      `}</style>

      <div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 lg:px-8 print:max-w-none print:px-0 print:py-0">
        <div className="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm print:border-zinc-300 print:shadow-none print:bg-white">
          <div className="flex flex-wrap items-start justify-between gap-4 print:hidden">
            <div>
              <Link
                href={`/owner/payouts/${year}/${String(month).padStart(2, "0")}`}
                className="text-sm font-medium text-zinc-700 underline-offset-4 hover:underline"
              >
                Back to month
              </Link>
              <h1 className="mt-2 text-2xl font-semibold tracking-tight">
                {settings.payoutStatementTitle}
              </h1>
            </div>

            <PrintButton className="rounded-2xl bg-zinc-950 px-4 py-3 text-sm font-medium text-white" />
          </div>

          <div className="hidden print:block">
            <h1 className="text-2xl font-semibold tracking-tight">
              {settings.payoutStatementTitle}
            </h1>
          </div>

          <div className="mt-4 grid gap-3 text-sm text-zinc-600 sm:grid-cols-2 print:text-black">
            <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Company
              </p>
              <p className="mt-1 text-base font-semibold text-zinc-950">
                {settings.businessName}
              </p>
            </div>
            <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Period
              </p>
              <p className="mt-1 text-base font-semibold text-zinc-950">
                {formatMonthLabel(year, month)}
              </p>
            </div>
            <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Generated by
              </p>
              <p className="mt-1 text-base font-semibold text-zinc-950">
                {profile.role === "owner" ? "Owner" : "Manager"} view
              </p>
            </div>
            <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Generated at
              </p>
              <p className="mt-1 text-base font-semibold text-zinc-950">
                {generatedAt}
              </p>
            </div>
          </div>

          <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5 print:grid-cols-5">
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Total approved sales
              </p>
              <p className="mt-2 text-xl font-semibold">{formatMoney(totals.approvedSales)}</p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Commission amount
              </p>
              <p className="mt-2 text-xl font-semibold">
                {formatMoney(totals.commissionAmount)}
              </p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Deductions
              </p>
              <p className="mt-2 text-xl font-semibold">{formatMoney(totals.deductions)}</p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Advance deduction
              </p>
              <p className="mt-2 text-xl font-semibold">
                {formatMoney(totals.advanceDeduction)}
              </p>
            </article>
            <article className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 print:bg-white">
              <p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">
                Final payable
              </p>
              <p className="mt-2 text-xl font-semibold">
                {formatMoney(totals.finalPayable)}
              </p>
            </article>
          </div>

          <div className="mt-6 grid gap-4">
            {monthData.payouts.map((payout) => (
              <article
                key={payout.staff_id}
                className="break-inside-avoid rounded-3xl border border-zinc-200 bg-white p-5 print:border-zinc-300 print:shadow-none"
              >
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <h2 className="text-lg font-semibold text-zinc-950">
                      {payout.staff_name || "Unknown staff"}
                    </h2>
                    <p className="mt-1 text-sm text-zinc-600">
                      {payout.approved_entries_count} approved entries
                    </p>
                  </div>
                  <span className="rounded-full bg-zinc-100 px-3 py-1 text-xs font-medium uppercase tracking-wide text-zinc-700 print:bg-zinc-200">
                    {payout.status === "paid" ? "Paid" : "Unpaid"}
                  </span>
                </div>

                <div className="mt-4 grid gap-3 text-sm text-zinc-700 sm:grid-cols-2 xl:grid-cols-4 print:text-black">
                  <div>
                    <span className="block text-zinc-500">Approved sales</span>
                    <span className="font-medium">
                      {formatMoney(Number(payout.total_approved_sales))}
                    </span>
                  </div>
                  <div>
                    <span className="block text-zinc-500">Commission %</span>
                    <span className="font-medium">
                      {Number(payout.commission_percentage).toFixed(2)}%
                    </span>
                  </div>
                  <div>
                    <span className="block text-zinc-500">Commission amount</span>
                    <span className="font-medium">
                      {formatMoney(Number(payout.commission_amount))}
                    </span>
                  </div>
                  <div>
                    <span className="block text-zinc-500">Final payable</span>
                    <span className="font-medium">
                      {formatMoney(Number(payout.final_payable))}
                    </span>
                  </div>
                </div>

                <div className="mt-4 grid gap-3 text-sm text-zinc-700 sm:grid-cols-2 print:text-black">
                  <div>
                    <span className="block text-zinc-500">Deductions</span>
                    <span className="font-medium">{formatMoney(Number(payout.deductions))}</span>
                  </div>
                  <div>
                    <span className="block text-zinc-500">Advance deduction</span>
                    <span className="font-medium">
                      {formatMoney(Number(payout.advance_deduction))}
                    </span>
                  </div>
                </div>
              </article>
            ))}
          </div>

          <div className="mt-6 rounded-2xl border border-zinc-200 bg-zinc-50 p-4 text-sm text-zinc-600 print:bg-white">
            Monthly commission is calculated only in monthly payouts at month end.
          </div>
        </div>
      </div>
    </main>
  );
}
